run:
  type: test # train or test
  num_episodes: 1000 # Number of episodes to run
  episode_time: 25 # Maximum episode time in seconds
  dt: 0.025 # Time step in seconds
  batch_size: 32 # Mini-batch size for training

model:
  type: DQN # DQN or REINFORCE
  discount_factor: 0.99 # Discount factor for future rewards
  learning_rate: 0.001 # Learning rate for the optimizer
  layer_sizes: [20, 20] # Number of neurons in each layer

  init_from_weights:
    enable: true
    file_name: "Layer2020_F2025.h5"
  save_weights:
    enable: true
    file_name: "testDQN.h5"
    save_frequency: 50 # Save weights every n episodes

  DQN_params:
    epsilon_init: 1 # Initial epsilon value (for epsilon-greedy policy)
    epsilon_min: 0.07 # Minimum epsilon value
    epsilon_decay: 0.995 # Epsilon decay rate

pendulum_env:
  length: 1.0 # Length of the pendulum
  mass_base: 1.0 # Mass of the base
  mass_bob: 1.0 # Mass of the bob



  